# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shamayoga - Learn to inspire. Learn to teach Yoga.
email: shamayoga9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shamayoga at the crossroads of the physical and the spiritual
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brave-poitras-ad569a.netlify.com" #"https://brave-poitras-ad569a.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: shamayoga
github_username:  shamayoga

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  
# -----------
# CloudCannon
# -----------
_options:
  layout:
    hidden: true
  content:
    bold: true	 
    italic: true 	 
    removeformat: true 	 
    link: true 	 
    undo: true 	 
    redo: true 	 
    underline: true	 
    strike: false 	 
    subscript: false 	 
    superscript: false 	 
    code: false	 
    format: p h1 h2 h3 h4 h5 h6 pre address div
    blockquote: true 	 
    numberedlist: true 	 
    bulletedlist: true	 
    outdent: true	 
    indent: true	 
    image: true 	 
    embed: true	 
    table: true
    styles: /css/editor.css
    left: align-left
    center: center-this-text
    right: align-right
    justify: full-width-text
  _html:
    bold: true	 
    italic: true 	 
    removeformat: true 	 
    link: true 	 
    undo: true 	 
    redo: true 	 
    format: p h3 h4 h5 h6 pre address div
    blockquote: true 	 
    numberedlist: true 	 
    bulletedlist: true	 
    image: true 
_editable_regions:
  image:
    url_src: true  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
